### ISSUE TITLE
Design: Страница регистрации

### ISSUE THREAD

**Issue by rogulenkoko** [rogulenkoko/FunkMap#4]
Регистрация в несколько этапов
1. Ввод базовой информации
Поля: логин, пароль, подтверждение пароля
так же сообщение об ошибке, о существующем логине
2. Подтверждение
2.1 Подтверждение через почту
Поля: email, поле для ввода ключа подтверждения
2.2 Подтверждение через Telegram
Поля: информация о имени бота в телеграме; текст сообщения которое надо отправить боту; кнопка за запроса проверки авторизации через телеграм
3. Успешная регистрация
Сообщение об успешной регистрации
На первом этапе пользователь решает каким образом будет подтвержден аккаунт. Думаю, что должно быть вверху представление некого пути (http://www.mp3cut.ru/) только с ветветлением в две стороны на втором этапе. А внизу уже поля каждого этапа

**Comment by VitalyGrigorjev** [comment]
Жду фидбэк.

**Comment by VitalyGrigorjev** [comment]
Исходник+превью

https://drive.google.com/open?id=0B3VWeKEo7dyydktxRUdYX2V4Sm8

**Comment by VitalyGrigorjev** [comment]
Исходник+превью

https://drive.google.com/drive/folders/0B3VWeKEo7dyyOHJjWmdZYjBHcHc

**Comment by rogulenkoko** [comment]
При подтверждении через email нужно добавить кнопку, при нажатии которой отправился этот самый код на имейл. А то как он его получит? и я бы сделал поле для кода такой же длины, как и для email

**Comment by VitalyGrigorjev** [comment]
Кнопку забыл, сделаем. Не имеет смысла делать поле большое, если у нас будет, к примеру, не больше 5 символов.

**Comment by VitalyGrigorjev** [comment]
Добавил кнопку.

Исходник+превью

https://drive.google.com/open?id=0B3VWeKEo7dyydGRkZjJJSTc1YXc
