### ISSUE TITLE
Design: Страница авторизации

### ISSUE THREAD

**Issue by rogulenkoko** [rogulenkoko/FunkMap#5]
Поля: логин, пароль, чекбокс (запомнить меня)
Есть возможность перейти на страницу регистрации

**Comment by VitalyGrigorjev** [comment]
Я считаю, что переход на страницу регистрации не обязателен, а вот "забыли пароль" и его восстановление было бы очень актуально.

**Comment by rogulenkoko** [comment]
Переходи на страницу регистрации не нужен, если в навигационной строке есть кнопка регистрации. Но имеет ли смысл ее туда выносить, если регистрируешься только один раз. а так бы на регистрацию можно было бы перейти через авторизацию и вверху на панеле была бы одна кнопка "войти" или "выйти" если юзер атвторизован.

**Comment by VitalyGrigorjev** [comment]
Одна кнопка войти или выйти меня бы сильно смутила. К примеру я данном ресурсе впервой и я буду оооочень долго искать кнопку регистрации.

**Comment by rogulenkoko** [comment]
Ну да, ты прав
